# Generated by Django 6.1 on 2026-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attended',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('interview', 'Interview'), ('meeting', 'Meeting'), ('followup', 'Follow-up'), ('networking', 'Networking event'), ('beratung', 'Beratungstermin / Meldetermin')], max_length=20),
        ),
    ]
