# Generated by Django 5.1.4 on 2025-01-21 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_jobs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
