# Generated by Django 5.1.4 on 2025-01-26 19:48

import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_set_skill_relationships"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skilltreemodel",
            name="count",
        ),
        migrations.RemoveField(
            model_name="skilltreemodel",
            name="level",
        ),
        migrations.RemoveField(
            model_name="skilltreemodel",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="skilltreemodel",
            name="path",
        ),
        migrations.RemoveField(
            model_name="skilltreemodel",
            name="protected",
        ),
        migrations.RemoveField(
            model_name="skilltreemodel",
            name="slug",
        ),
        migrations.AlterField(
            model_name="skilltreemodel",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="SkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(
                        default=0,
                        help_text="Internal counter of how many times this tag is in use",
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False,
                        help_text="Will not be deleted when the count reaches 0",
                    ),
                ),
                ("path", models.TextField()),
                (
                    "label",
                    models.CharField(
                        help_text="The name of the tag, without ancestors",
                        max_length=255,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1, help_text="The level of the tag in the tree"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="jobs.skilltag",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("slug", "parent")},
            },
            bases=(tagulous.models.models.BaseTagTreeModel, models.Model),
        ),
        migrations.AddField(
            model_name="skilltreemodel",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                autocomplete_view="jobs:skill_tags_autocomplete",
                blank=True,
                case_sensitive=False,
                force_lowercase=True,
                help_text="Enter hierarchical tags (e.g. programming/python/django)",
                initial="programming/web, programming/database, programming/mobile",
                max_count=10,
                space_delimiter=False,
                to="jobs.skilltag",
                tree=True,
            ),
        ),
    ]
