# Generated by Django 5.1.4 on 2025-01-26 12:01

import tagulous.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_skilltreemodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skilltreemodel",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                autocomplete_view="jobs:skill_tags_autocomplete",
                blank=True,
                case_sensitive=False,
                force_lowercase=True,
                help_text="Enter hierarchical tags (e.g. programming/python/django)",
                initial="programming/web, programming/database, programming/mobile",
                max_count=10,
                space_delimiter=False,
                to="jobs.skilltag",
                tree=True,
            ),
        ),
    ]
