# Generated by Django 6.1 on 2026-09-01 17:17

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('jobs', '0003_remove_skilltreemodel_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobskill',
            options={'verbose_name_plural': 'Job skills'},
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='skills',
            field=models.ManyToManyField(help_text='Skills linked to this job posting', related_name='jobs', through='jobs.JobSkill', to='jobs.skilltreemodel'),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='proficiency',
            field=models.CharField(choices=[('required', 'Required'), ('preferred', 'Preferred'), ('bonus', 'Nice to have')], default='required', max_length=20),
        ),
        migrations.AlterField(
            model_name='skilltreemodel',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon code (e.g. skill-icons:python)', max_length=100),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateField(verbose_name='Applied on')),
                ('employer_name', models.CharField(blank=True, max_length=200, verbose_name='Employer')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Job title')),
                ('employer_address', models.CharField(blank=True, max_length=300, verbose_name='Employer address')),
                ('employer_phone', models.CharField(blank=True, max_length=50, verbose_name='Employer phone')),
                ('employer_email', models.EmailField(blank=True, max_length=254, verbose_name='Employer e-mail')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Contact person')),
                ('channel', models.IntegerField(blank=True, choices=[(1, 'In person'), (2, 'Written'), (3, 'Phone'), (4, 'Online'), (5, 'E-mail')], null=True, verbose_name='Channel')),
                ('source', models.CharField(blank=True, choices=[('JOBBOERSE_BA', 'Jobbörse BA'), ('STEPSTONE', 'Stepstone'), ('LINKEDIN', 'LinkedIn'), ('COMPANY_SITE', 'Company website'), ('NEWSPAPER', 'Newspaper'), ('VERMITTLUNGSVORSCHLAG', 'Placement proposal'), ('INITIATIVE', 'Initiative'), ('OTHER', 'Other')], max_length=40, verbose_name='Source')),
                ('source_ref', models.CharField(blank=True, max_length=500, verbose_name='Source reference')),
                ('result', models.CharField(choices=[('OFFEN', 'Open'), ('EINGANG_BESTAETIGT', 'Receipt confirmed'), ('GESPRAECH', 'Interview'), ('ABSAGE', 'Rejected'), ('ZUSAGE', 'Accepted'), ('ZURUECKGEZOGEN', 'Withdrawn'), ('ABGEBROCHEN', 'Aborted')], default='OFFEN', max_length=30, verbose_name='Result')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='Result date')),
                ('result_note', models.CharField(blank=True, max_length=500, verbose_name='Result note')),
                ('effort_type', models.CharField(choices=[('BEWERBUNG', 'Application'), ('INITIATIV', 'Initiative application'), ('TELEFONAT', 'Phone call'), ('VORSPRACHE', 'Personal visit'), ('MASSNAHME', 'Measure'), ('JOBBOERSE', 'Job board search'), ('SONSTIGE', 'Other')], default='BEWERBUNG', max_length=30, verbose_name='Effort type')),
                ('related_to_vermittlungsvorschlag', models.BooleanField(default=False, verbose_name='Related to placement proposal')),
                ('costs_cents', models.PositiveIntegerField(default=0, verbose_name='Costs (cents)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job search effort',
                'verbose_name_plural': 'Job search efforts',
                'ordering': ['-applied_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40, verbose_name='Action')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Field')),
                ('old_value', models.TextField(blank=True, verbose_name='Old value')),
                ('new_value', models.TextField(blank=True, verbose_name='New value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='jobs.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/srv/django/jobless/media/evidence'), upload_to='evidence/%Y/%m', verbose_name='File')),
                ('evidence_type', models.CharField(choices=[('BEWERBUNG', 'Application copy'), ('ABSAGE', 'Rejection'), ('EINLADUNG', 'Invitation'), ('KOSTENBELEG', 'Cost receipt'), ('KONTOAUSZUG', 'Bank statement'), ('SONSTIGES', 'Other')], default='BEWERBUNG', max_length=30, verbose_name='Evidence type')),
                ('filename', models.CharField(blank=True, max_length=300, verbose_name='Filename')),
                ('mime', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Size')),
                ('sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='jobs.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence file',
                'verbose_name_plural': 'Evidence files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ObligationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid from')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid to')),
                ('required_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Required count')),
                ('period', models.CharField(choices=[('CALENDAR_MONTH', 'Calendar month'), ('ROLLING_30_DAYS', 'Rolling 30 days'), ('CUSTOM_RANGE', 'Custom range')], default='CALENDAR_MONTH', max_length=30, verbose_name='Period')),
                ('due_rule', models.CharField(choices=[('MONTH_END', 'Unaufgefordert bis Monatsende'), ('NEXT_MONTH_5', 'Bis zum 5. des Folgemonats'), ('APPOINTMENT', 'Zum Beratungstermin mitbringen'), ('OTHER', 'Sonstiges')], default='MONTH_END', max_length=30, verbose_name='Due rule')),
                ('due_rule_notes', models.CharField(blank=True, max_length=200, verbose_name='Due rule notes')),
                ('accepted_channels', models.JSONField(blank=True, default=list, verbose_name='Accepted channels')),
                ('proof_form', models.CharField(choices=[('BA_MINIMAL', 'BA-Minimal'), ('JOBCENTER_LIST', 'Jobcenter-Liste'), ('CUSTOM_COLUMNS', 'Custom columns')], default='JOBCENTER_LIST', max_length=30, verbose_name='Proof form')),
                ('notes', models.TextField(blank=True, verbose_name='Notes (verbatim)')),
                ('counts_interviews_as_effort', models.BooleanField(default=False, verbose_name='Interviews count as effort')),
                ('counts_measures_as_effort', models.BooleanField(default=False, verbose_name='Measures count as effort')),
                ('counts_jobboard_search_as_effort', models.BooleanField(default=False, verbose_name='Job board search counts as effort')),
                ('last_submitted_on', models.DateField(blank=True, null=True, verbose_name='Last submitted on')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caseworker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligation_plans', to='contacts.contact', verbose_name='Caseworker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obligation plan',
                'verbose_name_plural': 'Obligation plans',
                'ordering': ['-valid_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('BA_MINIMAL', 'BA-Minimal'), ('JOBCENTER_LIST', 'Jobcenter-Liste'), ('CUSTOM_COLUMNS', 'Custom columns')], max_length=30, verbose_name='Export profile')),
                ('period_from', models.DateField(verbose_name='Period from')),
                ('period_to', models.DateField(verbose_name='Period to')),
                ('submitted_on', models.DateField(auto_now_add=True, verbose_name='Submitted on')),
                ('rows', models.PositiveIntegerField(default=0, verbose_name='Rows')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Note')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='jobs.obligationplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_on'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Full name')),
                ('kundennummer', models.CharField(blank=True, max_length=50, verbose_name='Kundennummer')),
                ('bg_nummer', models.CharField(blank=True, max_length=50, verbose_name='BG-Nummer')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('regime', models.CharField(choices=[('ALG1', 'ALG I — Agentur für Arbeit'), ('GRUNDSICHERUNG', 'Grundsicherung/Bürgergeld — Jobcenter'), ('NONE', 'None')], default='NONE', max_length=20, verbose_name='Regime')),
                ('office_name', models.CharField(blank=True, max_length=200, verbose_name='Office')),
                ('preferred_locale', models.CharField(default='de-DE', max_length=20, verbose_name='Preferred locale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nachweis_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'applied_on'], name='jobs_applic_user_id_81e2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', '-created_at'], name='jobs_applic_user_id_ed0464_idx'),
        ),
    ]
