# Generated by Django 5.1.4 on 2025-01-26 12:12

from django.db import migrations


def sync_skills_and_tags(apps, schema_editor):
    SkillTreeModel = apps.get_model('jobs', 'SkillTreeModel')
    db_alias = schema_editor.connection.alias
    
    # Update all skills
    for skill in SkillTreeModel.objects.using(db_alias).all():
        if skill.name and not skill.tags:
            skill.tags = skill.name
            skill.save()


def reverse_sync(apps, schema_editor):
    # No reverse operation needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_skilltreemodel_tags"),
    ]

    operations = [
        migrations.RunPython(sync_skills_and_tags, reverse_sync),
    ]
