# Generated by Django 6.1 on 2026-09-01 17:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobskill_options_alter_jobposting_skills_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obligationplan',
            name='instrument',
            field=models.CharField(choices=[('EGV', 'Eingliederungsvereinbarung (§ 37 SGB III)'), ('KOOPERATIONSPLAN', 'Kooperationsplan (§ 15 SGB II)'), ('VERPFLICHTUNGSBESCHEID', 'Verpflichtungsbescheid (§ 15a SGB II)'), ('NONE', 'None')], default='NONE', max_length=30, verbose_name='Legal instrument'),
        ),
        migrations.AddField(
            model_name='obligationplan',
            name='nachweis_cost_rule',
            field=models.CharField(blank=True, max_length=300, verbose_name='Who pays the costs of proof (verbatim)'),
        ),
        migrations.AddField(
            model_name='obligationplan',
            name='which_efforts',
            field=models.TextField(blank=True, verbose_name='Which efforts (verbatim)'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='From')),
                ('to_date', models.DateField(verbose_name='To')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='Destination')),
                ('notified_on', models.DateField(blank=True, null=True, verbose_name='Notified on')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Not yet reported'), ('NOTIFIED', 'Notified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected / not approved')], default='PENDING', max_length=20, verbose_name='Approval status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Absence (Ortsabwesenheit)',
                'verbose_name_plural': 'Absences (Ortsabwesenheit)',
                'ordering': ['from_date'],
            },
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('kind', models.CharField(choices=[('ILLNESS', 'Illness'), ('CHILDCARE', 'Childcare / care'), ('NO_VACANCIES', 'No suitable vacancies'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='Kind')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obstacles', to='jobs.evidencefile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstacles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obstacle / wichtiger Grund',
                'verbose_name_plural': 'Obstacles / wichtige Gründe',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vermittlungsvorschlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=200, verbose_name='Employer')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Job title')),
                ('received_on', models.DateField(default=datetime.date.today, verbose_name='Received on')),
                ('apply_by', models.DateField(blank=True, null=True, verbose_name='Apply by')),
                ('has_rechtsfolgenbelehrung', models.BooleanField(default=False, verbose_name='Rechtsfolgenbelehrung included')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('APPLIED', 'Applied'), ('DECLINED_WICHTIGER_GRUND', 'Declined — wichtiger Grund'), ('IGNORED', 'Ignored')], default='OPEN', max_length=30, verbose_name='Status')),
                ('source_ref', models.CharField(blank=True, max_length=500, verbose_name='Source reference')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vermittlungsvorschlaege', to='jobs.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vermittlungsvorschlaege', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vermittlungsvorschlag',
                'verbose_name_plural': 'Vermittlungsvorschläge',
                'ordering': ['apply_by', '-received_on'],
            },
        ),
    ]
