# Generated by Django 6.1 on 2026-09-01 18:07

import django.db.models.deletion
import django_tagulous.models.fields
import django_tagulous.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_obligationplan_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eigenbemuehungen', to='jobs.jobposting', verbose_name='Linked job posting'),
        ),
        migrations.CreateModel(
            name='ApplicationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(django_tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AddField(
            model_name='application',
            name='tags',
            field=django_tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='jobs:application_tags_autocomplete', blank=True, case_sensitive=False, force_lowercase=True, help_text='Tags, comma-separated (e.g. remote, handwerk, vertrieb)', space_delimiter=False, to='jobs.applicationtag'),
        ),
    ]
