"""Module containing skill icon mappings and utilities"""

DARK_VARIANTS = {
    icon_name: f"{icon_name}-dark"
    for icon_name in [
        'skill-icons:ableton', 'skill-icons:activitypub', 'skill-icons:actix',
        'skill-icons:aiscript', 'skill-icons:alpinejs', 'skill-icons:anaconda',
        'skill-icons:androidstudio', 'skill-icons:angular', 'skill-icons:apple',
        'skill-icons:arch', 'skill-icons:autocad', 'skill-icons:aws',
        'skill-icons:azure', 'skill-icons:bash', 'skill-icons:bevy',
        'skill-icons:bitbucket', 'skill-icons:blender', 'skill-icons:bsd',
        'skill-icons:bun', 'skill-icons:cassandra', 'skill-icons:clion',
        'skill-icons:clojure', 'skill-icons:cloudflare', 'skill-icons:cmake',
        'skill-icons:codepen', 'skill-icons:coffeescript', 'skill-icons:crystal',
        'skill-icons:cypress', 'skill-icons:d3', 'skill-icons:dart',
        'skill-icons:debian', 'skill-icons:deno', 'skill-icons:devto',
        'skill-icons:discordjs', 'skill-icons:dynamodb', 'skill-icons:eclipse',
        'skill-icons:elasticsearch', 'skill-icons:elixir', 'skill-icons:elysia',
        'skill-icons:emotion', 'skill-icons:expressjs', 'skill-icons:fediverse',
        'skill-icons:figma', 'skill-icons:flask', 'skill-icons:flutter',
        'skill-icons:gcp', 'skill-icons:gherkin', 'skill-icons:github',
        'skill-icons:githubactions', 'skill-icons:gitlab', 'skill-icons:gmail',
        'skill-icons:godot', 'skill-icons:gradle', 'skill-icons:grafana',
        'skill-icons:graphql', 'skill-icons:gtk', 'skill-icons:haskell',
        'skill-icons:haxe', 'skill-icons:haxeflixel', 'skill-icons:hibernate',
        'skill-icons:htmx', 'skill-icons:idea', 'skill-icons:ipfs',
        'skill-icons:java', 'skill-icons:jenkins', 'skill-icons:julia',
        'skill-icons:kali', 'skill-icons:kotlin', 'skill-icons:ktor',
        'skill-icons:laravel', 'skill-icons:latex', 'skill-icons:less',
        'skill-icons:linux', 'skill-icons:lit', 'skill-icons:lua',
        'skill-icons:markdown', 'skill-icons:mastodon', 'skill-icons:materialui',
        'skill-icons:matlab', 'skill-icons:maven', 'skill-icons:mint',
        'skill-icons:misskey', 'skill-icons:mysql', 'skill-icons:neovim',
        'skill-icons:nestjs', 'skill-icons:netlify', 'skill-icons:nextjs',
        'skill-icons:nim', 'skill-icons:nix', 'skill-icons:nodejs',
        'skill-icons:notion', 'skill-icons:npm', 'skill-icons:nuxtjs',
        'skill-icons:obsidian', 'skill-icons:octave', 'skill-icons:opencv',
        'skill-icons:openstack', 'skill-icons:php', 'skill-icons:phpstorm',
        'skill-icons:pinia', 'skill-icons:pkl', 'skill-icons:plan9',
        'skill-icons:planetscale', 'skill-icons:pnpm', 'skill-icons:postgresql',
        'skill-icons:powershell', 'skill-icons:processing', 'skill-icons:pug',
        'skill-icons:pycharm', 'skill-icons:python', 'skill-icons:pytorch',
        'skill-icons:qt', 'skill-icons:r', 'skill-icons:rabbitmq',
        'skill-icons:raspberrypi', 'skill-icons:react', 'skill-icons:reactivex',
        'skill-icons:redhat', 'skill-icons:redis', 'skill-icons:regex',
        'skill-icons:remix', 'skill-icons:replit', 'skill-icons:rider',
        'skill-icons:rollupjs', 'skill-icons:ros', 'skill-icons:scala',
        'skill-icons:scikitlearn', 'skill-icons:sequelize', 'skill-icons:sketchup',
        'skill-icons:solidjs', 'skill-icons:spring', 'skill-icons:stackoverflow',
        'skill-icons:sublime', 'skill-icons:supabase', 'skill-icons:svg',
        'skill-icons:symfony', 'skill-icons:tailwindcss', 'skill-icons:tauri',
        'skill-icons:tensorflow', 'skill-icons:terraform', 'skill-icons:threejs',
        'skill-icons:ubuntu', 'skill-icons:unity', 'skill-icons:v',
        'skill-icons:vercel', 'skill-icons:vim', 'skill-icons:visualstudio',
        'skill-icons:vite', 'skill-icons:vitest', 'skill-icons:vscode',
        'skill-icons:vscodium', 'skill-icons:vuejs', 'skill-icons:vuetify',
        'skill-icons:webpack', 'skill-icons:webstorm', 'skill-icons:windicss',
        'skill-icons:windows', 'skill-icons:workers', 'skill-icons:yarn',
        'skill-icons:yew', 'skill-icons:zig', 'skill-icons:html', 'skill-icons:css',
    ]
}

SKILL_ICONS = (
    ('skill-icons:ableton', 'Ableton'),
    ('skill-icons:activitypub', 'ActivityPub'),
    ('skill-icons:actix', 'Actix'),
    ('skill-icons:aiscript', 'AIScript'),
    ('skill-icons:alpinejs', 'Alpine.js'),
    ('skill-icons:anaconda', 'Anaconda'),
    ('skill-icons:androidstudio', 'Android Studio'),
    ('skill-icons:angular', 'Angular'),
    ('skill-icons:apple', 'Apple'),
    ('skill-icons:arch', 'Arch Linux'),
    ('skill-icons:autocad', 'AutoCAD'),
    ('skill-icons:aws', 'Amazon Web Services'),
    ('skill-icons:azure', 'Azure'),
    ('skill-icons:bash', 'Bash'),
    ('skill-icons:bevy', 'Bevy'),
    ('skill-icons:bitbucket', 'Bitbucket'),
    ('skill-icons:blender', 'Blender'),
    ('skill-icons:bsd', 'BSD'),
    ('skill-icons:bun', 'Bun'),
    ('skill-icons:cassandra', 'Cassandra'),
    ('skill-icons:clion', 'CLion'),
    ('skill-icons:clojure', 'Clojure'),
    ('skill-icons:cloudflare', 'Cloudflare'),
    ('skill-icons:cmake', 'CMake'),
    ('skill-icons:codepen', 'CodePen'),
    ('skill-icons:coffeescript', 'CoffeeScript'),
    ('skill-icons:crystal', 'Crystal'),
    ('skill-icons:cypress', 'Cypress'),
    ('skill-icons:d3', 'D3.js'),
    ('skill-icons:dart', 'Dart'),
    ('skill-icons:debian', 'Debian'),
    ('skill-icons:deno', 'Deno'),
    ('skill-icons:devto', 'Dev.to'),
    ('skill-icons:discordjs', 'Discord.js'),
    ('skill-icons:dynamodb', 'DynamoDB'),
    ('skill-icons:eclipse', 'Eclipse'),
    ('skill-icons:elasticsearch', 'Elasticsearch'),
    ('skill-icons:elixir', 'Elixir'),
    ('skill-icons:elysia', 'Elysia'),
    ('skill-icons:emotion', 'Emotion'),
    ('skill-icons:expressjs', 'Express.js'),
    ('skill-icons:fediverse', 'Fediverse'),
    ('skill-icons:figma', 'Figma'),
    ('skill-icons:flask', 'Flask'),
    ('skill-icons:flutter', 'Flutter'),
    ('skill-icons:gcp', 'Google Cloud Platform'),
    ('skill-icons:gherkin', 'Gherkin'),
    ('skill-icons:github', 'GitHub'),
    ('skill-icons:githubactions', 'GitHub Actions'),
    ('skill-icons:gitlab', 'GitLab'),
    ('skill-icons:gmail', 'Gmail'),
    ('skill-icons:godot', 'Godot'),
    ('skill-icons:gradle', 'Gradle'),
    ('skill-icons:grafana', 'Grafana'),
    ('skill-icons:graphql', 'GraphQL'),
    ('skill-icons:gtk', 'GTK'),
    ('skill-icons:haskell', 'Haskell'),
    ('skill-icons:haxe', 'Haxe'),
    ('skill-icons:haxeflixel', 'HaxeFlixel'),
    ('skill-icons:hibernate', 'Hibernate'),
    ('skill-icons:htmx', 'htmx'),
    ('skill-icons:idea', 'IntelliJ IDEA'),
    ('skill-icons:ipfs', 'IPFS'),
    ('skill-icons:java', 'Java'),
    ('skill-icons:jenkins', 'Jenkins'),
    ('skill-icons:julia', 'Julia'),
    ('skill-icons:kali', 'Kali Linux'),
    ('skill-icons:kotlin', 'Kotlin'),
    ('skill-icons:ktor', 'Ktor'),
    ('skill-icons:laravel', 'Laravel'),
    ('skill-icons:latex', 'LaTeX'),
    ('skill-icons:less', 'Less'),
    ('skill-icons:linux', 'Linux'),
    ('skill-icons:lit', 'Lit'),
    ('skill-icons:lua', 'Lua'),
    ('skill-icons:markdown', 'Markdown'),
    ('skill-icons:mastodon', 'Mastodon'),
    ('skill-icons:materialui', 'Material-UI'),
    ('skill-icons:matlab', 'MATLAB'),
    ('skill-icons:maven', 'Maven'),
    ('skill-icons:mint', 'Mint'),
    ('skill-icons:misskey', 'Misskey'),
    ('skill-icons:mysql', 'MySQL'),
    ('skill-icons:neovim', 'Neovim'),
    ('skill-icons:nestjs', 'NestJS'),
    ('skill-icons:netlify', 'Netlify'),
    ('skill-icons:nextjs', 'Next.js'),
    ('skill-icons:nim', 'Nim'),
    ('skill-icons:nix', 'Nix'),
    ('skill-icons:nodejs', 'Node.js'),
    ('skill-icons:notion', 'Notion'),
    ('skill-icons:npm', 'npm'),
    ('skill-icons:nuxtjs', 'Nuxt.js'),
    ('skill-icons:obsidian', 'Obsidian'),
    ('skill-icons:octave', 'Octave'),
    ('skill-icons:opencv', 'OpenCV'),
    ('skill-icons:openstack', 'OpenStack'),
    ('skill-icons:php', 'PHP'),
    ('skill-icons:phpstorm', 'PhpStorm'),
    ('skill-icons:pinia', 'Pinia'),
    ('skill-icons:pkl', 'PKL'),
    ('skill-icons:plan9', 'Plan 9'),
    ('skill-icons:planetscale', 'PlanetScale'),
    ('skill-icons:pnpm', 'pnpm'),
    ('skill-icons:postgresql', 'PostgreSQL'),
    ('skill-icons:powershell', 'PowerShell'),
    ('skill-icons:processing', 'Processing'),
    ('skill-icons:pug', 'Pug'),
    ('skill-icons:pycharm', 'PyCharm'),
    ('skill-icons:python', 'Python'),
    ('skill-icons:pytorch', 'PyTorch'),
    ('skill-icons:qt', 'Qt'),
    ('skill-icons:r', 'R'),
    ('skill-icons:rabbitmq', 'RabbitMQ'),
    ('skill-icons:raspberrypi', 'Raspberry Pi'),
    ('skill-icons:react', 'React.js'),
    ('skill-icons:reactivex', 'ReactiveX'),
    ('skill-icons:redhat', 'Red Hat'),
    ('skill-icons:redis', 'Redis'),
    ('skill-icons:regex', 'Regex'),
    ('skill-icons:remix', 'Remix'),
    ('skill-icons:replit', 'Replit'),
    ('skill-icons:rider', 'Rider'),
    ('skill-icons:rollupjs', 'Rollup.js'),
    ('skill-icons:ros', 'ROS'),
    ('skill-icons:scala', 'Scala'),
    ('skill-icons:scikitlearn', 'scikit-learn'),
    ('skill-icons:sequelize', 'Sequelize'),
    ('skill-icons:sketchup', 'SketchUp'),
    ('skill-icons:solidjs', 'Solid.js'),
    ('skill-icons:spring', 'Spring'),
    ('skill-icons:stackoverflow', 'Stack Overflow'),
    ('skill-icons:sublime', 'Sublime Text'),
    ('skill-icons:supabase', 'Supabase'),
    ('skill-icons:svg', 'SVG'),
    ('skill-icons:symfony', 'Symfony'),
    ('skill-icons:tailwindcss', 'Tailwind CSS'),
    ('skill-icons:tauri', 'Tauri'),
    ('skill-icons:tensorflow', 'TensorFlow'),
    ('skill-icons:terraform', 'Terraform'),
    ('skill-icons:threejs', 'Three.js'),
    ('skill-icons:ubuntu', 'Ubuntu'),
    ('skill-icons:unity', 'Unity'),
    ('skill-icons:v', 'V'),
    ('skill-icons:vercel', 'Vercel'),
    ('skill-icons:vim', 'Vim'),
    ('skill-icons:visualstudio', 'Visual Studio'),
    ('skill-icons:vite', 'Vite'),
    ('skill-icons:vitest', 'Vitest'),
    ('skill-icons:vscode', 'VS Code'),
    ('skill-icons:vscodium', 'VSCodium'),
    ('skill-icons:vuejs', 'Vue.js'),
    ('skill-icons:vuetify', 'Vuetify'),
    ('skill-icons:webpack', 'Webpack'),
    ('skill-icons:webstorm', 'WebStorm'),
    ('skill-icons:windicss', 'WindiCSS'),
    ('skill-icons:windows', 'Windows'),
    ('skill-icons:workers', 'Workers'),
    ('skill-icons:yarn', 'Yarn'),
    ('skill-icons:yew', 'Yew'),
    ('skill-icons:zig', 'Zig')
)

ICON_NAME_MAPPING = {
    'Adobe After Effects': 'skill-icons:aftereffects',
    'Adobe Illustrator': 'skill-icons:illustrator',
    'Adobe Photoshop': 'skill-icons:photoshop',
    'Adobe Premiere': 'skill-icons:premierepro',
    'Adobe XD': 'skill-icons:xd',
    'Amazon Web Services': 'skill-icons:aws',
    'C Sharp': 'skill-icons:cs',
    'CSS': 'skill-icons:css',
    'Express.js': 'skill-icons:expressjs',
    'FastAPI': 'skill-icons:fastapi',
    'HTML': 'skill-icons:html',
    'JavaScript': 'skill-icons:javascript',
    'MongoDB': 'skill-icons:mongodb',
    'Next.js': 'skill-icons:nextjs',
    'Node.js': 'skill-icons:nodejs',
    'PostgreSQL': 'skill-icons:postgresql',
    'Ruby on Rails': 'skill-icons:rails',
    'React.js': 'skill-icons:react',
    'TypeScript': 'skill-icons:typescript',
    'Vue.js': 'skill-icons:vuejs',
    'scikit-learn': 'skill-icons:scikitlearn',
    'Tailwind CSS': 'skill-icons:tailwindcss',
    'Unreal Engine': 'skill-icons:unrealengine',
    'WebAssembly': 'skill-icons:webassembly',
    'AI': 'eos-icons:ai',
    'AU': 'skill-icons:audition',
    'Bots': 'skill-icons:discordbots',
    'Express': 'skill-icons:expressjs',
    'Firebase': 'devicon:firebase',
    'Go': 'skill-icons:golang',
    'Markdown': 'skill-icons:markdown',
    'PowerShell': 'skill-icons:powershell',
    'PR': 'skill-icons:premiere',
    'Python': 'skill-icons:python-dark',
}
